mlcommons/modelbench

README.md

Add context, clean up examples, explain new features.
Note that this doesn't include how to run your own SUT; support for that will come in a later PR.

Rewrite docs for public launch.

---

.github/workflows/python-app.yml
README.md
poetry.lock
pyproject.toml

Making the PR mainly to trigger workflows.

Trying other Python versions

---

README.md

Add instructions for running the benchmark on your SUT

---

.github/workflows/docker.yml

Github Actions is ridiculous. This attempts to address that.

fixing-docker-image

---

src/modelbench/benchmark_runner.py
src/modelbench/run.py
src/modelbench/static_site_generator.py

Hopefully fixes https://github.com/mlcommons/modelbench/issues/453
Just a few small things that only make a difference when running a custom SUT. We should probably add a smoke test for this, but let's talk about what form that should take.

Quick fix for small issues with custom SUTs

---

src/modelgauge/tests/safe_v1.py

Hindi locale string was incorrect.

fix incorrect locale string

---

src/modelgauge/tests/safe_v1.py

This addresses an error in the locale string (HI_HI instead of HI_IN).

Update prompt file version

---

src/modelgauge/annotator_set.py
src/modelgauge/default_annotator_set.py
src/modelgauge/private_ensemble_annotator_set.py
src/modelgauge/tests/safe_v1.py
tests/modelgauge_tests/test_default_annotator_set.py
tests/modelgauge_tests/test_private_ensemble_annotator_set.py
tests/modelgauge_tests/test_safe.py

PR #455 merged in modelgauge from commit 44d1a0da36b10176f3d1aeb15e569d54cbb93f45.  This PR merges in the last dangling changes from modelgauge PR 560.

Complete modelgauge merge

---

src/modelbench/benchmark_runner.py
tests/modelbench_tests/test_benchmark_runner.py

Aha! I found it. The cause: I shot myself in the foot with a standard python footgun. Not sure how to test for this in the general case. Is there a linter that would catch this?

Fix measurement bug

---

.github/workflows/scheduled-smoke-test.yml

The smoke test keeps breaking for extended periods. Since we're all in discord, let's have it post there.

auto-grumble on smoke test failure

---

poetry.lock
pyproject.toml
src/modelbench/benchmark_runner.py
src/modelbench/run.py
src/modelbench/run_journal.py
src/modelgauge/pipeline.py
src/modelgauge/suts/together_client.py
tests/modelbench_tests/test_benchmark_runner.py
tests/modelbench_tests/test_run_journal.py

Added a number of small improvements and fixes to make things work better when running things.

Run ops improvements

---

src/modelbench/benchmarks.py
tests/modelbench_tests/test_benchmark.py

fix how AI is capitalized

---

src/modelbench/consistency_checker.py

This adds the missing prompt counts.

More details in consistency check outputs

---

tests/modelgauge_tests/test_caching.py

The sample_cache.sqlite file was often changed for mysterious reasons. This fixes the problem and removes the footgun that was causing it.

fix spurious sample_cache.sqlite changes

---

plugins/huggingface/modelgauge/suts/huggingface_api.py
plugins/validation_tests/test_object_creation.py

Adding olmo-2 with a newly created HF endpoint

---

tests/modelgauge_tests/test_prompt_sets.py

This was causing errors on my machine with python 3.10.10.

Fix fstring quotation marks

---

src/modelgauge/locales.py
src/modelgauge/prompt_sets.py
tests/modelgauge_tests/test_locales.py

https://github.com/mlcommons/modelbench/issues/889

add chinese prompt sets

---

src/modelbench/run.py
src/modelgauge/instance_factory.py
src/modelgauge/suts/together_client.py

https://github.com/mlcommons/modelbench/issues/917

Add SUTs for Chinese

---

src/modelbench/standards.json

This is required to run the benchmarks.

calibration run on 2,736 Chinese practice prompts

---

src/modelbench/benchmark_runner.py
src/modelbench/run.py
tests/modelbench_tests/test_run.py

Automated consistency checking after every run.

automated consistency check

---

plugins/validation_tests/test_object_creation.py

https://github.com/mlcommons/modelbench/issues/982
Works 
https://github.com/mlcommons/modelbench-private/actions/runs/14499580559

skip baseten SUT, because it's very expensive to run

---

plugins/huggingface/modelgauge/suts/huggingface_chat_completion.py

This model is not available on hf-inference

llama 3.1 8b uses nebius

---

src/modelgauge/annotation_pipeline.py
src/modelgauge/main.py
src/modelgauge/pipeline_runner.py
tests/modelgauge_tests/test_annotation_pipeline.py
tests/modelgauge_tests/test_cli.py
tests/modelgauge_tests/test_pipeline_runner.py

Users can request `--ensemble` to be run with `run-job` or `run-csv-items`.

Run ensemble in modelgauge CLI

---

plugins/validation_tests/test_object_creation.py

Of course I thought of this 2 seconds after merging in the dedicated together SUT PR 🙃

Remove dedicated together SUT from smoke test

---

plugins/amazon/modelgauge/suts/aws_bedrock_client.py

add premier

---

plugins/huggingface/modelgauge/suts/huggingface_sut_factory.py
plugins/huggingface/tests/test_huggingface_sut_factory.py
src/modelgauge/command_line.py
src/modelgauge/dynamic_sut_factory.py
src/modelgauge/dynamic_sut_finder.py
src/modelgauge/dynamic_sut_metadata.py
src/modelgauge/suts/together_sut_factory.py
tests/modelbench_tests/test_run.py
tests/modelgauge_tests/test_dynamic_sut_finder.py
tests/modelgauge_tests/test_dynamic_sut_metadata.py

and in so doing:
* improve exceptions
* improve documentation in comments
* add logic to try to parse an old SUT UID as if it were a dynamic SUT

clarify provider vs driver nomenclature

---

src/modelgauge/suts/meta_llama_client.py
tests/modelgauge_tests/test_meta_llama.py

https://github.com/mlcommons/modelbench/issues/1083

Remove hack required by a bug that is now fixed

---

src/modelgauge/config.py
tests/modelgauge_tests/test_config.py

This searches *all the way* to the root.

Search up tree for config

---

src/modelbench/benchmark_runner.py

in the one-sut-per-run changes but shouldn't have.  
https://github.com/mlcommons/modelbench/issues/1135

fix suts key in starting run journal entry that became sut 

---

src/modelgauge/private_ensemble_annotator_set.py
src/modelgauge/suts/together_client.py

Swap mixtral endpoint for ensemble annotator

---

src/modelbench/cli.py

Found this little bug while working on https://github.com/mlcommons/modelbench/issues/1163

fix mistyped variable

---

src/modelbench/cli.py
src/modelgauge/cli.py
src/modelgauge/sut.py
tests/modelbench_tests/test_run.py

The rich SUT UID PoC only added that capability to modelgauge.run_sut. This PR adds it elsewhere.
https://github.com/mlcommons/modelbench/issues/1192

Add rich sut uids everywhere

---

src/modelgauge/suts/openai_client.py
tests/modelgauge_tests/sut_tests/test_openai_client.py

https://github.com/mlcommons/modelbench/issues/1197

update openai API after max_tokens deprecation

---

src/modelbench/benchmark_runner.py

Add annotation details to `translated_annotation` journal entry.

Add annotation details to journal.

---

src/modelgauge/suts/huggingface_sut_factory.py

This was causing failures when I tried to update modelbench in modelbench-private

fix f string

---

src/modelbench/consistency_checker.py
tests/modelbench_tests/test_consistency_checker.py

Updates #1121 to address #1284 .

Allow more types of empty responses in consistency checker.

---

src/modelgauge/suts/azure_client.py

Bump the retries for Azure, specifically phi 3.5.

retry harder with Azure SUTs

---

poetry.lock
pyproject.toml
tests/modelgauge_tests/test_cli.py

Update all libraries, fix tests to match new behavior.

Dependency update

---

docs/add-a-sut.md
src/modelgauge/annotator.py
src/modelgauge/annotators/demo_annotator.py
src/modelgauge/annotators/llama_guard_annotator.py
src/modelgauge/annotators/openai_compliance_annotator.py
src/modelgauge/annotators/perspective_api.py
src/modelgauge/annotators/prompt_engineered_annotator.py
src/modelgauge/sut.py
src/modelgauge/suts/anthropic_api.py
src/modelgauge/suts/aws_bedrock_client.py
src/modelgauge/suts/azure_client.py
src/modelgauge/suts/baseten_api.py
src/modelgauge/suts/demo_01_yes_no_sut.py
src/modelgauge/suts/demo_02_secrets_and_options_sut.py
src/modelgauge/suts/demo_03_sut_with_args.py
src/modelgauge/suts/google_genai.py
src/modelgauge/suts/google_generativeai.py
src/modelgauge/suts/huggingface_api.py
src/modelgauge/suts/huggingface_chat_completion.py
src/modelgauge/suts/meta_llama_client.py
src/modelgauge/suts/nvidia_nim_api_client.py
src/modelgauge/suts/openai_client.py
src/modelgauge/suts/together_client.py
tests/modelgauge_tests/fake_annotator.py
tests/modelgauge_tests/fake_classes.py
tests/modelgauge_tests/fake_sut.py
tests/modelgauge_tests/sut_tests/test_together_client.py

First portion of William's simplifications.

Remove generic types
