src/modelbench/hazards.py

This addresses the pydantic deprecation warning that was appearing when running tests:
`PydanticDeprecatedSince20: Support for class-based config is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.7/migration/`

Replace Hazard's deprecated config class

---

src/modelbench/run.py
src/modelbench/static_site_generator.py
src/modelbench/templates/content/suts.toml
tests/test_run.py
tests/test_static_site_generator.py

Now users should be able to run a benchmark for any registered ModelGauge SUT via the `-s` option. Also add some very basic defaulting for SUT static content so that reports will render.

Add ability to benchmark dynamic SUT

---

poetry.lock
pyproject.toml
src/modelbench/modelgauge_runner.py

This dramatically reduces the amount of time it takes to run `modelbench --help`. It's about 2x as fast on the first run (from 5.5ish seconds to 2.5ish seconds) and about 3x as fast on subsequent runs (from 1ish second to .33ish seconds).
I suspect installs will be sped up as well.

Remove unnecessary plugins

---

src/modelbench/run.py

This allows running the `grid` and `responses` commands on user-specified SUTs.
Addresses #237

Add --sut flag to grid and responses commands

---

README.md
docs/add-a-sut.md
poetry.lock

Add tutorial for the simplest way to add a new SUT to ModelBench. Note: this will not work with the version of ModelBench on PyPi. We will have to do a release. If you want to test this, install either from this branch in Git or from your local filesystem.

Docs for SUTs

---

src/modelbench/benchmarks.py
src/modelbench/hazards.py
src/modelbench/uid.py
tests/test_benchmark.py
tests/test_uid.py

Machinery for consistent UIDs. See the uids.py file and associated tests for documentation on how it works.

Add HasUid and apply it to Benchmark and Hazard.

---

src/modelbench/run.py
src/modelbench/static_site_generator.py
src/modelbench/utilities.py
tests/test_utilities.py

This adds a progress tracker to benchmark runs, which can be used to print out machine-readable progress updates (e.g. for modellab) by setting the `--machine-reports` flag. If this flag is set, none of the regular print statements will be logged either, so as to not confuse the machine. To accomplish that, I had to replace the `click.echo` statements with logging statements.
Right now the progress tracker just prints a dictionary containing % complete. But we can easily add more information to it in the future if needed.
Progress can only be measured at the test-level at the moment. If we decide that this generally the direction we want to go in for progress reporting, then I can go ahead and update modelgauge so that progress can be calculated at the test-item level.
In addition to …

Machine-readable progress updates

---

src/modelbench/utilities.py
tests/test_utilities.py

The progress tracker optionally sends its progress as a dict to stdout.  Sugar consumes that and does string manipulation to change the quotes to make it parseable as json. This ensures the dict is printed out in a format that is json parseable as-is, without string manipulations. 
Addresses [this comment](https://github.com/mlcommons/sugar/pull/32/files#r1733406407)

output dict in json format for consumption

---

src/modelbench/run.py
src/modelbench/static_site_generator.py
src/modelbench/utilities.py
tests/test_utilities.py

Output with `--machine-reports --parallel true` flags from before:
After this change:
Let me know if this is what we want.

Always print progress bar

---

src/modelbench/record.py
tests/test_record.py

This makes the benchmark record look like this: [benchmark_record-general_purpose_ai_chat_benchmark-1.0.json](https://github.com/user-attachments/files/17031659/benchmark_record-general_purpose_ai_chat_benchmark-1.0.json)
It looks like this:
```
"_metadata": {
"format_version": 1,
"run": {
"user": "william",
"timestamp": "2024-09-17 12:55:36 UTC",
"platform": "Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35",
"system": "Linux 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J",
"node": "loewen",
"python": "3.10.12"
},
"code": {
"source": {
"git_version": "git version 2.34.1",
"origin": "git@github.com:mlcommons/modelbench.git",
"code_version": "v0.5.1-43-gc9749253",
"changed_files": [
"M src/modelbench/record.py",
"M tests/test_record.py"
]
}, …
```

Put code info in run record

---

.gitignore
plugins/huggingface/modelgauge/suts/huggingface_inference.py
plugins/huggingface/tests/test_huggingface_inference.py
src/modelgauge/auth/huggingface_inference_token.py
src/modelgauge/auth/together_key.py
src/modelgauge/auth/vllm_key.py
src/modelgauge/suts/together_client.py
src/modelgauge/tests/safe_v1.py
tests/modelgauge_tests/test_safe.py

The HuggingFace token was referred to as api_key in some places. This PR makes the naming consistent.
Together with that change, the token/key secret classes are moved out of the client code that uses them and into their own modules, so they can be imported into client code and tests and other modules.

Call the HuggingFace token a token consistently

---

plugins/huggingface/modelgauge/suts/huggingface_inference.py

Registers a mistral-nemo huggingface SUT that points to workstream 3's dedicated huggingface endpoint. 
Note: WS3 keeps this endpoint paused when not in use. `HuggingFaceInferenceSUT` automatically resumes an endpoint if it's scaled to 0. But paused endpoints need to be manually started. If this becomes an issue, we can change the SUT to automatically resume paused endpoints as well.

Register mistral nemo

---

src/modelbench/benchmark_runner.py
src/modelgauge/tests/safe_v1.py
tests/modelbench_tests/test_benchmark_runner.py

PR #487 did not apply its test annotator instantiation change to modelbench's runner. This fixes that.
I also snuck in a bug fix for the "sxc" prompt issue that was causing some tests to fail.

Benchmark runner instantiates annotators

---

tests/modelgauge_tests/test_cli.py

This fixes the failing python 3.12 test.

Annotator runner test doesn't consider order of items

---

.github/workflows/python-app.yml
src/modelbench/benchmark_runner.py
src/modelbench/cache.py
src/modelbench/run.py
src/modelgauge/pipeline.py
tests/modelbench_tests/test_benchmark_runner.py
tests/modelbench_tests/test_cache.py

Adds some basic cache information at the end. I'm thinking we'll add more over time; this was just enough to try to debug a problem in the runner.
```
Cache info:
sut_cache: DiskCache(run/sut_cache)
sut_cache: started with 0
sut_cache: finished with 60
annotator_cache: DiskCache(run/annotator_cache)
annotator_cache: started with 0
annotator_cache: finished with 60
```

Show cache info at the end of the run

---

.github/workflows/scheduled-smoke-test.yml

* stop creating issues, as we don't look at them
* reenable the benchmark runs as part of the test

Smoke test improvements

---

src/modelbench/run.py
src/modelgauge/annotators/llama_guard_annotator.py
src/modelgauge/dependency_helper.py
src/modelgauge/tests/safe_v1.py
tests/modelbench_tests/test_run.py
tests/modelgauge_tests/test_safe.py

Use final practice prompts. Also disable non-English locales, as we no longer have prompts for them.

Use final practice prompts

---

src/modelgauge/tests/safe_v1.py
tests/modelgauge_tests/test_safe.py

Since we currently only have English prompts, remove non-English locales from smoke tests.

Fix smoke tests

---

src/modelbench/benchmark_runner.py
src/modelbench/benchmark_runner_items.py
src/modelgauge/private_ensemble_annotator_set.py
tests/modelbench_tests/test_benchmark_runner.py

Add a little more journaling.
Make sure our external resources are live before starting a massive run.

More ops fixes

---

docs/run-journal.md

No feedback on the journal docs, so I guess we'll merge this and then add to it later.

Add some basic journal documentation

---

src/modelgauge/private_ensemble_annotator_set.py
tests/modelgauge_tests/test_private_ensemble_annotator_set.py

The public version of this is mainly cleanup; the private version adds more tests.

More elaborate private tests, saner public tests.

---

src/modelbench/consistency_checker.py
src/modelbench/run.py
src/modelbench/run_journal.py
tests/modelbench_tests/test_consistency_checker.py

I don't particularly like this. I think the class hierarchy is too complicated. My general goal was to make it easy to 1) add new checks and 2) understand what each check does. 
I didn't put any effort towards efficiently querying the journal, so there's room for optimization there.
I only added a handful of checks to demonstrate what this looks like. Once we decide on the approach we want to take here, I will add some more easy checks + some basic unit testing with sample run journals.
Here is what the output of a sample run looks like:
```
Results for Test x SUT level checks
Entity                           EachPromptRespondedToOnce    EachResponseTranslatedOnce    EachItemMeasuredOnce
-------------------------------  ---------------------------  ---------------------------- …
```

Journal consistency checker

---

plugins/anthropic/modelgauge/suts/anthropic_api.py
plugins/huggingface/modelgauge/suts/huggingface_api.py
plugins/openai/modelgauge/suts/openai_client.py
src/modelgauge/suts/together_client.py

Some SUTs didn't retry at all; others have built-in retry that's set pretty low. Let's see how this does in production.

More consistent retrying

---

src/modelbench/benchmark_runner.py
tests/modelbench_tests/test_benchmark_runner.py

Note: we should come back to this and create separate caches for each annotator (and SUT?).

Fix annotator cache bug in benchmark runner

---

src/modelbench/benchmarks.py
src/modelbench/hazards.py
src/modelbench/scoring.py
tests/modelbench_tests/test_scoring.py
tests/modelbench_tests/test_static_site_generator.py

This primarily replaces the hardcoded "30% unsafe is the worst possible score" logic with a cutoff based on the reference score.

Tweak the grading function

---

tests/modelgauge_tests/test_cli.py

ensure the CLI tool's output order is deterministic

---

plugins/huggingface/pyproject.toml

https://github.com/huggingface/huggingface_hub/issues/2671

update huggingface sdk to solve date parsing issue 

---

README.md

I guess this is all we need for a release?

Release prep

---

src/modelbench/benchmarks.py
tests/modelbench_tests/data/standards_amazing.json
tests/modelbench_tests/data/standards_middling.json
tests/modelbench_tests/data/standards_poor.json
tests/modelbench_tests/test_benchmark_grading.py

Fix the problem where benchmark scoring combines official and practice prompts for the standard. Now official and practice each have their own standards.
This shifts responsibility for  knowing a benchmark's standard to the BenchmarkDefinition, in parallel with how it works for hazards. Between this and the 0.5 legacy stuff this leaves a lot of dead or deprecated code, but I didn't want to mess with too much for an emergency fix.

Benchmark scoring fix.

---

src/modelbench/consistency_checker.py
src/modelbench/run.py
tests/modelbench_tests/test_consistency_checker.py
tests/modelgauge_tests/test_cli.py

Summary of changes:
- CLI 'consistency-check` command accepts path to journal file *or* directory which will be recursively searched for journal files, all of which will be checked.
- If multiple journals are checked, a summary table will be printed at the end.
- Checker objects don't hold memory intensive journal-querying object anymore. This was prohibitive for running checks on multiple large journals.
- To improve robustness, try to get a test's annotator set directly from the test. If that doesn't work (e.g. don't have the right secrets), then get the annotator set from the journals annotator-related entries.
- More tests
- More checks

More consistency checks + improvements

---

plugins/mistral/modelgauge/suts/mistral_client.py
plugins/mistral/modelgauge/suts/mistral_sut.py
plugins/mistral/tests/test_mistral_sut.py

Note: This changes the cache keys for the already existing mistral SUTs. So the old caches won't work for them.

Mistral SUTs with moderation

---

src/modelgauge/tests/safe_v1.py

This fixes a bug that requires you to have the secret prompts token even when running the public practice prompts. I believe this will also address some issues we're encountering in the smoke tests.

Fix secrets bug in SafeTest

---

plugins/validation_tests/test_object_creation.py

until we deal with localized prompt files in a more dignified way.
Currently, the smoke test appears to do the cross product of locale x prompt file to generate test items. This leads to a situation where it tries to collect fr_fr prompts from a file that only contains en_us prompts, and as a result the test fails.
The failure was useful in identifying a logic bug in the locale x prompt file handling, which we already knew needs a good cleanup.
This PR puts in a workaround to skip the fr_fr prompts in the test only. There will be a separate PR to clean up the prompt file handling.

hack so we can get value out of the test 

---

src/modelbench/benchmark_runner.py
tests/modelbench_tests/test_benchmark_runner.py

This fixes the cache collision bug for SUTs in modelbench. I also added some more cache testing.
This is a simple fix-- it just prepends the SUT UID to the cache key. We should discuss if it makes sense for all the SUTs to share one cache or if we would benefit from having one cache per SUT. Same for the annotators.

Fix cache bug

---

src/modelgauge/main.py

This adds `list-annotators` to the CLI, which is complementary to the already existing `list-suts` and `list-tests`. This command is useful for debugging.

Add list-annotators command

---

tests/modelgauge_tests/data/install_pyproject.toml

This add Python 3.12 to the supported versions. It's [required for modelbench-private tests and what we support in the Dockerfile](https://github.com/mlcommons/modelbench-private/pull/38#discussion_r1910406195).

update supported python versions

---

src/modelbench/benchmarks.py
src/modelbench/hazards.py
src/modelbench/run.py
src/modelgauge/locales.py
src/modelgauge/prompt_sets.py
src/modelgauge/tests/safe_v1.py
tests/modelbench_tests/test_benchmark.py
tests/modelbench_tests/test_record.py
tests/modelbench_tests/test_run.py
tests/modelgauge_tests/fake_dependency_helper.py
tests/modelgauge_tests/test_prompt_sets.py
tests/modelgauge_tests/test_safe.py

https://github.com/mlcommons/modelbench/issues/781
https://github.com/mlcommons/modelbench/pull/744
https://github.com/mlcommons/modelbench/pull/780
New uploaded files need to be added to the `PROMPT_SETS` dict in `src/modelgauge/prompt_sets.py` and they need to contain the whole key. E.g. if you want to use the key "demo_hi_in" then your prompt file name should include "demo_hi_in" in it.
To use new prompt sets in modellab, you need to add them to the modellab drop down, and to the modelrunner list of prompt sets. We may want to change that so it's less manual.

Decouple the prompt set type (practice, official) from its file name

---

src/modelbench/standards.json

French official tandards using "gemma-2-9b-it-hf", "phi-3.5-mini-instruct"

Update French official standards

---

docs/run-journal.md
src/modelbench/benchmark_runner.py
tests/modelbench_tests/test_benchmark_runner.py

Right now there is no easy way to identify which test is associated with which hazard using the journal alone. This adds another entry to the journal with some extra hazard info.

Add hazard info to journal

---

plugins/mistral/modelgauge/suts/mistral_client.py

This results in 0 rate limit exceptions on my machine on a test of 1200 samples.

Increase mistral backoff

---

plugins/validation_tests/test_object_creation.py
src/modelgauge/instance_factory.py
src/modelgauge/prompt_sets.py
src/modelgauge/tests/safe_v1.py
tests/config/secrets.toml
tests/modelgauge_tests/fake_secrets.py
tests/modelgauge_tests/test_safe.py

https://github.com/mlcommons/modelbench/issues/860
This PR addresses two related issues:
* modelbench refuses to run if you don't have a prompt set download token in your secrets.toml file, even if you want to use the demo prompt set, which doesn't require a token.
* unit tests use the practice prompt set, which requires a token. To make this work, a hack was introduced in the `fake_all_secrets` function calls to use the real value for the prompt set download token.

remove token requirement to download demo prompt set

---

plugins/google/modelgauge/suts/google_genai_client.py
plugins/huggingface/modelgauge/suts/huggingface_chat_completion.py
plugins/mistral/modelgauge/suts/mistral_client.py
plugins/mistral/modelgauge/suts/mistral_sut.py
plugins/nvidia/modelgauge/suts/nvidia_nim_api_client.py
plugins/openai/modelgauge/suts/openai_client.py
src/modelgauge/retry_decorator.py
tests/modelgauge_tests/test_retry_decorator.py

A retry decorator that SUTs can use on their `evaluate` method. It is designed around the idea that there are two types of exceptions: those that should only retried a handful of times and those that should be more persistently retried until success (e.g. rate limits).

Retry decorator

---

.github/workflows/python-app.yml
plugins/google/modelgauge/suts/google_genai_client.py
plugins/validation_tests/test_object_creation.py
poetry.lock
src/modelgauge/prompt_sets.py
tests/modelgauge_tests/test_prompt_sets.py

Some tests download real prompt sets, which may require an auth token.
Instead of monkeypatching the secrets to use the auth token defined in the real secrets just for the test, we replace prompt set URLs with their demo equivalents.
https://github.com/mlcommons/modelbench-private/issues/53

use public prompt sets instead of prompt sets that require auth

---

src/modelgauge/annotation_pipeline.py
src/modelgauge/command_line.py
src/modelgauge/main.py
src/modelgauge/pipeline_runner.py
src/modelgauge/prompt_pipeline.py
tests/modelgauge_tests/test_cli.py

First attempt at an analytics CLI tool: `run-csv`.
To summarize, each run results in a new directory containing the output results file and a metadata json file.
The output structure is largely based off of the sample dvc directory in the modelbench-private `dvc-experiments` branch. However, I was not able to follow it 100%. Here are the key differences:
- The metadata lists `suts` instead of one `sut`. This is because the pipeline runner is shared with the already-exisiting `run-csv-ITEMS` which allows for multi-sut runs.
- I changed the `prompts` metadata key to `input` in order to generalize to runs where the input is prompts + responses.
- It is not currently possible to include `provider` and `provider_id` in the metadata. The best I could do is include the SUT initialization record. …

Analytics cli

---

src/modelgauge/prompt_pipeline.py
tests/modelgauge_tests/test_prompt_pipeline.py

If you run a modelgauge test using an official prompt set csv file as input, modelgauge rejects it because the column names don't match what it expects.
This adds support for:
* official prompt set files
* database dumps using the table column names
https://github.com/mlcommons/modelbench/issues/901

Accept official CSV prompt files and database dumps as inputs

---

src/modelgauge/annotation_pipeline.py
src/modelgauge/prompt_pipeline.py
tests/modelgauge_tests/test_annotation_pipeline.py
tests/modelgauge_tests/test_pipeline_runner.py
tests/modelgauge_tests/test_prompt_pipeline.py

The pipeline runner (which used by `run-job` and `run-csv-items`) now will keep retrying calls to SUTs and annotators until it gets a successful response. It logs exceptions and retry counts so that a user can manually stop the command if they see that it is retrying an impossible exception a million times.

Pipeline retries

---

.gitignore
src/modelgauge/main.py
src/modelgauge/pipeline_runner.py
tests/modelgauge_tests/test_pipeline_runner.py

- Update .gitignore to include default directory used by `run-job`
- The logger.info() statements weren't printing anything before. Now they print to stdout.

Misc. run-job improvements 

---

.github/workflows/python-app.yml

Sometimes a poetry.lock file isn't refreshed by a developer. This adds a check so we get feedback about it early (at least earlier than the smoke test).
A pre-commit hook is also an option, but not everyone likes those. People who do are welcome to add them to their local repo.

add poetry lock file check

---

plugins/baseten/modelgauge/suts/baseten_api.py

The baseten endpoint sometimes takes too long to spin up, resulting in a `ConnectionError` exception. This PR modifies the SUT to retry that specific exception for a whole day (instead of just 3 times).
I also modified the SUT UID to be consistent with the other nvidia sut.

Retry connection exceptions for baseten suts

---

plugins/validation_tests/test_object_creation.py

Increase timeout from 20 min to 25 min to accommodate Baseten.

Longer smoketest timeout

---

plugins/validation_tests/test_object_creation.py

This is for card 974: Refactor smoke tests to include only one SUT per provider and only serverless
- Only include one SUT per class. SUT classes roughly correspond to providers, but some providers have multiple SUT classes (e.g. for different endpoints/apis).
- Skip SUTs that belong to non-serverless classes ($$). Right now this just includes huggingface inference and baseten.
- This now requires you to have specific plugins installed to run the validation tests due to imports of class names. It will break without those plugins installed. Maybe this is undesirable?

Lighter smoke tests

---

plugins/vertexai/modelgauge/suts/vertexai_client.py
plugins/vertexai/modelgauge/suts/vertexai_mistral_sut.py
plugins/vertexai/tests/test_vertexai_mistral_sut.py

VertexAI made some changes in the last few days. This includes request formatting and no longer supporting mistral-large-2407.
Thank you Roger for figuring this out with me:)

Vertexai fixes

---

.gitignore
README.md
tests/modelbench_tests/test_run.py

* Adds a mock annotator for use in the unit tests, so we don't need a together key to run the tests. (Closes #1021 )
* Minor doc update + .gitignore update.

Mock annotator for tests 

---

poetry.lock
pyproject.toml

We had the plugins defined both in the main dependencies (as `{version = "*", optional = true}`) and the dev dependencies (with `{path=..., develop = true, optional = true}`.
When using modelbench as a dependency in another pyproject file as below, I wasn't able to generate a lock:
```
modelbench = {git = "https://github.com/mlcommons/modelbench.git", extras = ["all_plugins"], rev= "test-plugin-cleanup"}
```
The error message:
```
Because modelbench[all-plugins] (1.0.0) @ git+https://github.com/mlcommons/modelbench.git@HEAD depends on modelgauge_amazon (*) which doesn't match any versions, modelbench is forbidden.
```
The issue is that it's resolving `modelgauge_amazon` with the first definition, not the second. 
With this PR, there's only one definition. I left in the develop / optional …

Ensuring path is defined for extras.

---

plugins/huggingface/modelgauge/suts/huggingface_chat_completion.py
plugins/huggingface/tests/test_huggingface_chat_completion.py
src/modelgauge/secret_values.py
src/modelgauge/suts/together_client.py

There's a matching branch in modelbench-private for the changes there.

Switch to new together annotator.

---

src/modelgauge/suts/meta_llama_client.py

The Llama API is returning things that are invalid according to their Pydantic definitions, but this somehow doesn't show up as a problem until cache retrieval. Here I'm just fixing the data to match its typing. Maybe there's a better option?

Fix Pydantic issue with cached values.

---

src/modelgauge/suts/together_client.py

If the endpoint isn't started, you get the following error when running a benchmark with a dedicated together SUT:
```
self.endpoint_status = response.json()["state"]
~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'state'
```
This error occurs specifically when running multi-threaded benchmarks because a request to start the endpoint when it's already starting will result in an error response.
This PR fixes this issue.

Dedicated together SUT bug

---

src/modelbench/benchmark_runner.py
tests/modelbench_tests/test_benchmark_runner.py

This does not have quite the level of testing I'd like, as all of our tests are in terms of the measurement 'badness', while our production stuff is 'is_safe'. The code also feels weirdly specific for what's otherwise generic code. But it's the best fix I can find for now.

Adding initial code to make empty responses safe

---

plugins/huggingface/modelgauge/suts/huggingface_sut_factory.py

When trying to run dynamic SUTs directly on huggingface, the code only looked for a dedicated endpoint. Now it looks for a serverless option as well.

try both serverless and dedicated until you find a place to run your model

---

src/modelgauge/annotation_pipeline.py
src/modelgauge/data_schema.py
src/modelgauge/dataset.py
src/modelgauge/pipeline_runner.py
src/modelgauge/prompt_pipeline.py
src/modelgauge/single_turn_prompt_response.py
tests/modelgauge_tests/test_annotation_pipeline.py
tests/modelgauge_tests/test_cli.py
tests/modelgauge_tests/test_data_schema.py
tests/modelgauge_tests/test_dataset.py
tests/modelgauge_tests/test_pipeline_runner.py
tests/modelgauge_tests/test_prompt_pipeline.py

The overall goal of this PR is to standardize data formatting so that the outputs of one stage can be used as the input of another. And to avoid head aches.
Two new objects are instrumental in accomplishing this:
1) The Data Schema objects, which define column names in one place.
2) Dataset objects which handle both reading from input and writing to output.
- The different types of datasets will read CSV rows and output the relevant object for each row e.g. TestItem for prompts, SUTInteraction for prompts-responses, and AnnotatedSUTInteraction for annotations.
- The Annotation dataset serializes/deserializes annotations as json-strings. It can serialize pydantic objects or dictionaries. Annotations will always be deserialized as dictionaries.
Also in service of this goal, every output …

Standardize columns + Data refactor

---

src/modelbench/consistency_checker.py
tests/modelbench_tests/test_consistency_checker.py

Previously, blank responses would be scored by the evaluator. Now they are always safe. The production code was updated a while ago; this should bring the consistency checker up to date.

Update consistency checker to approve of our fix for blank responses.

---

src/modelgauge/suts/together_sut_factory.py
tests/modelgauge_tests/sut_tests/test_together_sut_factory.py

Together's `models` API is broken. Roger opened an [issue](https://github.com/togethercomputer/together-python/issues/343) 2 weeks ago that has still not been acknowledged.
This is one of the issues causing smoke test failures.
This PR fixes the issue by no longer relying on the `models` call.

Fix together dynamic factory

---

src/modelgauge/suts/meta_llama_client.py
tests/modelgauge_tests/sut_tests/test_together_sut_factory.py

- I guess `Llama-4-Maverick-17B-128E-Instruct-FP8` is also unauthorized now
- Smoke test bug in together dynamic factory

Final smoke test fixes

---

src/modelgauge/pipeline_runner.py

I noticed that while we pass the `cache_dir` to the `PromptSUTWorkers`, we don't pass it to the `AnnotatorWorkers`. There doesn't seem to be a good reason for not doing this.

Allow annotator workers to cache.

---

src/modelbench/cli.py
tests/modelbench_tests/test_run.py

These are the new benchmark commands:
- `benchmark general <options>`
- `benchmark security <options>`
The grouping doesn't actually do anything at this moment. I was thinking of attaching the common benchmark options to the `benchmark` group, but then you would have to do
`benchmark --sut sut  <other common options> general --prompt-set practice <other benchmark specific options>`
And I think it would be annoying to have to keep track of which options go where. But this sets us up to move  other common benchmark behavior to this group level in the future.

benchmark cli groups

---

src/modelgauge/tests/demo_01_simple_qa_test.py
src/modelgauge/tests/demo_02_unpacking_dependency_test.py

It had to point to the last PR branch to allow the CI to pass. But now that it's on main, we can clean up.

Update source URLs in demo tests to point to the main branch

---

src/modelgauge/config.py
tests/modelgauge_tests/test_config.py

so that it's easier to figure out where it's looking in non-CLI use cases.

Improve error message for missing secrets 

---

src/modelgauge/annotation_pipeline.py
tests/modelgauge_tests/test_annotation_pipeline.py
tests/modelgauge_tests/test_pipeline_runner.py

Ran into an issue where we had a prompt dataset with unique prompt ids, but a duplicate prompt (which produced a duplicate response).
The way our caching works was the key is based only on the request/response text, but the value is the "whole" row, including the prompt uid.
If we had a file like:
```csv
prompt_uid,prompt,response
ppp,prompt0,response0
qqq,prompt0,response0
...
```
We'd end up with output like:
```csv
prompt_uid,prompt,response,annotations...
ppp,prompt0,response0,...
ppp,prompt0,response0,...
```
We'll probably want to discuss a larger fix, but this fix minimally handles the issue above.
Output of the new test before the changes applied:
```
FAILED tests/modelgauge_tests/test_pipeline_runner.py::TestAnnotatorRunner::test_cache_responses - AssertionError: assert {'p0', …
```

Duplicate prompt/response pairs with unique prompt ids

---

src/modelbench/benchmarks.py
src/modelbench/cli.py
src/modelbench/hazards.py
src/modelbench/standards.json
src/modelgauge/prompt_sets.py
src/modelgauge/tests/safe_v1.py
src/modelgauge/tests/security.py
tests/modelbench_tests/test_benchmark.py
tests/modelbench_tests/test_run.py
tests/modelgauge_tests/test_prompt_sets.py
tests/modelgauge_tests/test_safe.py
tests/modelgauge_tests/test_security.py

Prepare infrastructure for adding more security prompt sets.
Should not require any changes to modellab because the new --prompt_set and --locale options have defaults.

Security prompt sets

---

src/modelgauge/annotators/openai_compliance_annotator.py
src/modelgauge/annotators/prompt_engineered_annotator.py
src/modelgauge/auth/openai_compatible_secrets.py
src/modelgauge/dynamic_sut_factory.py
src/modelgauge/dynamic_sut_metadata.py
src/modelgauge/sut.py
src/modelgauge/sut_definition.py
src/modelgauge/sut_factory.py
src/modelgauge/suts/huggingface_sut_factory.py
src/modelgauge/suts/openai_client.py
src/modelgauge/suts/openai_sut_factory.py
src/modelgauge/suts/together_sut_factory.py
tests/modelbench_tests/test_run.py
tests/modelgauge_tests/data/sutdef.json
tests/modelgauge_tests/fake_secrets.py
tests/modelgauge_tests/sut_tests/test_huggingface_sut_factory.py
tests/modelgauge_tests/sut_tests/test_openai_client.py
tests/modelgauge_tests/sut_tests/test_openai_sut_factory.py
tests/modelgauge_tests/sut_tests/test_together_sut_factory.py
tests/modelgauge_tests/test_cli.py
tests/modelgauge_tests/test_dynamic_sut_factory.py
tests/modelgauge_tests/test_dynamic_sut_metadata.py
tests/modelgauge_tests/test_sut_definition.py
tests/modelgauge_tests/test_sut_factory.py

This allows you to use the existing OpenAI client for compatible SUTs running on different providers (not just openai's hardware).
Runing gpt models on OpenAI's hardware works as dynamic SUTs, so they don't need to be registered anymore:
`poetry run modelgauge run-sut --sut openai/gpt-4o:openai --prompt "why did the chicken cross the road?"`
You can do the same thing for SUTs that support the OpenAI API Spec, including any SUTs running in vllm, like this:
Add the credentials to `secrets.toml`:
```
[demo]
api_key = "a real key"
```
Add a factory for it to `openai_sut_factory.py` (it must include `base_url`):
```python
class DemoOpenAICompatibleSUTFactory(OpenAIGenericSUTFactory):
def __init__(self, raw_secrets, **kwargs):
super().__init__(raw_secrets)
self.provider = "demo"
self.base_url = …
```

Add ability to choose the openai driver for SUTs not deployed on openai

---

src/modelgauge/annotator.py
src/modelgauge/annotators/prompt_engineered_annotator.py
src/modelgauge/single_turn_prompt_response.py
src/modelgauge/tests/security.py

Security annotators require a context item and therefore special checks.

security annotator ready check

---

src/modelgauge/pipeline_runner.py
tests/modelgauge_tests/fake_annotator.py
tests/modelgauge_tests/fake_ensemble.py
tests/modelgauge_tests/test_pipeline_runner.py

My last [PR](https://github.com/mlcommons/modelbench/pull/1239) introduced a bug to the EnsembleRunner where we weren't capturing the correct part of the response in the readiness check. Also updated the tests so they'd have caught the error.

Fix EnsembleRunner

---

src/modelgauge/tests/security.py
tests/modelgauge_tests/test_security.py

The security annotator requires a seed_prompt in the context. As a quick fix, this duplicates the naive prompt text into the seed prompt context. But in the future I would like annotators to be able to handle two different types of test items: regular items and "security" items (#1246)

Make naive test compatible with security annotator
